services:
  - type: web
    name: rp-jewellers
    env: node
    region: singapore # Choose a region closest to your users
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # This should be set in the Render dashboard
      - key: RENDER_DATABASE_URL
        sync: false # This should be set in the Render dashboard
      - key: SESSION_SECRET
        generateValue: true
      - key: DB_SSL
        value: true
      - key: INITIALIZE_SAMPLE_ORDERS
        value: false
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - server/**
        - client/**
        - shared/**
        - package.json
        - vite.config.ts